export const Colors = {
  WHITE: '#FFFFFF',
  LIGHT_BG: '#F5F5F5',
  GRAY_BG: '#EEEEEE',
  DARK_GRAY_BG: '#DDDDDD',
  ERROR_BG: '#FFE5E5',
  ERROR_TEXT: '#FF3B30',
  INFO_TEXT: '#007AFF',
  MUTED_TEXT: '#666666',
  LIGHT_MUTED_TEXT: '#999999',
};
